# Generated by Django 5.2.10 on 2026-02-04 17:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeRecherche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la période')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Période active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Période de recherche',
                'verbose_name_plural': 'Périodes de recherche',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du statut')),
                ('code', models.CharField(default='', max_length=50, unique=True, verbose_name='Code technique')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('poste_occupe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste occupé')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='URL LinkedIn')),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom'], name='candidature_nom_83fe37_idx'), models.Index(fields=['email'], name='candidature_email_5da906_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entreprise', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('poste', models.CharField(max_length=200, verbose_name='Poste')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('contrat', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('ALTERNANCE', 'Alternance'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance'), ('AUTRE', 'Autre'), ('INTERIM', 'Intérim')], max_length=20, verbose_name='Type de contrat')),
                ('canal', models.CharField(blank=True, max_length=200, verbose_name='Canal')),
                ('date_candidature', models.DateField(default=django.utils.timezone.now, verbose_name='Date de candidature')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('statut_contextuel', models.JSONField(blank=True, null=True, verbose_name='Informations contextuelles du statut')),
                ('date_statut', models.DateField(default=django.utils.timezone.now, verbose_name='Date du statut')),
                ('priorite', models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('NORMALE', 'Normale'), ('ELEVEE', 'Élevée')], max_length=20, verbose_name='Priorité')),
                ('priorite_source', models.CharField(blank=True, choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique')], max_length=20, verbose_name='Source de la priorité')),
                ('date_priorite', models.DateField(blank=True, null=True, verbose_name='Date de la priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('contacts', models.ManyToManyField(blank=True, related_name='candidatures', to='candidatures.contact', verbose_name='Contacts')),
                ('periode_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='candidatures.perioderecherche', verbose_name='Période de recherche')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='candidatures.statut', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCandidature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('CV', 'CV'), ('LETTRE_MOTIVATION', 'Lettre de motivation'), ('PORTFOLIO', 'Portfolio'), ('TEST_TECHNIQUE', 'Test technique'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('chemin_fichier', models.CharField(default='', max_length=500, verbose_name='Chemin du fichier')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('taille', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidatures.candidature', verbose_name='Candidature')),
            ],
            options={
                'verbose_name': 'Document de candidature',
                'verbose_name_plural': 'Documents de candidature',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='PisteCandidature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entreprise', models.CharField(default='', max_length=200, verbose_name='Entreprise')),
                ('poste_cible', models.CharField(blank=True, max_length=200, verbose_name='Poste ciblé')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('url_annonce', models.URLField(blank=True, verbose_name="URL de l'annonce")),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('etat', models.CharField(choices=[('A_ETUDIER', 'À étudier'), ('A_CONTACTER', 'À contacter'), ('EN_PREPARATION', 'En préparation'), ('ABANDONNEE', 'Abandonnée'), ('TRANSFORMEE', 'Transformée')], default='A_ETUDIER', max_length=20, verbose_name='État')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pistes_source', to='candidatures.candidature', verbose_name='Candidature associée')),
                ('contacts', models.ManyToManyField(blank=True, related_name='pistes_candidature', to='candidatures.contact', verbose_name='Contacts')),
                ('periode_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes', to='candidatures.perioderecherche', verbose_name='Période de recherche')),
            ],
            options={
                'verbose_name': 'Piste de candidature',
                'verbose_name_plural': 'Pistes de candidature',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['date_candidature'], name='candidature_date_ca_2376de_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['entreprise'], name='candidature_entrepr_913c89_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['poste'], name='candidature_poste_de5d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['priorite'], name='candidature_priorit_befad5_idx'),
        ),
    ]
